title: RWG2 at UA-Tripods
email: cscheid@cs.arizona.edu
description: RWG2 - Visualization and Interpretation
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ua-tripods.github.io/rwg2/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
